import sys
import datetime
import argparse
import update_prices
import analyze_portfolio
import json
import pandas as pd
import os

def update_config_date():
    """Ensure the config file allows fetching up to today."""
    try:
        with open("data.json", 'r') as f:
            data = json.load(f)
        
        # Set latest_date to today so the data is updated up to the current date
        data['latest_date'] = datetime.datetime.now().strftime('%Y-%m-%d')
        
        with open("data.json", 'w') as f:
            json.dump(data, f, indent=4)
    except Exception:
        pass # If fails, we trust the user's config

def main():
    parser = argparse.ArgumentParser(description="Run daily updates for Pokemon Tracker")
    parser.add_argument("--incremental", action="store_true", help="Resume from last tracked date")
    parser.add_argument("--rebuild-from", help="Rebuild starting from specific date (YYYY-MM-DD)")
    args = parser.parse_args()

    print("========================================")
    print(f"  POKEMON TRACKER - DAILY UPDATE")
    print(f"  Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("========================================")

    # Determine Resume Date
    resume_date = None
    if args.rebuild_from:
         resume_date = args.rebuild_from
         print(f"  MODE: Rebuild from {resume_date}")
    elif args.incremental:
         if os.path.exists("daily_tracker.csv"):
             try:
                 df = pd.read_csv("daily_tracker.csv")
                 if not df.empty:
                     df['Date'] = pd.to_datetime(df['Date'])
                     last_date = df['Date'].max()
                     resume_date = (last_date + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
                     print(f"  MODE: Incremental update from {resume_date}")
                 else:
                     print("  MODE: Full Rebuild (CSV empty)")
             except Exception as e:
                 print(f"  Warning: Could not read tracker CSV ({e}). Full rebuild.")
         else:
             print("  MODE: Full Rebuild (No CSV)")
    else:
         print("  MODE: Full Rebuild (Default)")

    # Step 0: Auto-extend the config date so we don't get stuck in the past
    update_config_date()

    # Step 1: Fetch latest prices from the web
    print("\n>>> STEP 1: Updating Historical Prices...")
    try:
        update_prices.main()
    except Exception as e:
        print(f"CRITICAL ERROR in Price Update: {e}")
        # We continue even if price update fails, to at least see current basis
        # content with old prices

    # Step 2: Recalculate Portfolio Value & Basis
    print("\n>>> STEP 2: Analyzing Portfolio Performance...")
    try:
        analyze_portfolio.run_analysis(resume_date=resume_date)
    except Exception as e:
        print(f"CRITICAL ERROR in Analysis: {e}")
        sys.exit(1)

    # Step 3: Generate Summary JSON for Widget (Serverless)
    # NOTE: This is now handled inside analyze_portfolio.py to include 'history' for the graph
    print("\n>>> STEP 3: summary.json generated by analysis.")


    print("\n========================================")
    print("  UPDATE COMPLETE")
    print("  1. transactions.csv : Processed")
    print("  2. daily_tracker.csv: Updated")
    print("  3. portfolio_graph.html: Refreshed")
    print("========================================")

if __name__ == "__main__":
    main()
